#!/usr/bin/env bash
# This script displays "Best School" 10 times,
# "bad luck" for the 4th iteration,
# and "good luck" for the 8th iteration.

i=1
while [ $i -le 10 ]
do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  i=$((i + 1))
done

