#!/usr/bin/env bash
# this script display numbers from 1 to 20
# and show specific" bad lack" messages for 4 9 and 17
i=1
while [ $i -le 20 ]
do
 echo "$i"
 case $i in
   4)
    echo "bad luck from china"
    ;;
   9)
    echo "bad luck from japan"
    ;;
   17)
    echo "bad luck from Italy"
    ;;
esac
i=$((i + 1))
done
