#!/usr/bin/env bash
# This script lists non-hidden files and displays part after the first dash
#ls | cut -d '-' -f2
#ls | while read line; do cut -d '-' -f2; done
for line in *; do
    echo "$line" | cut -d '-' -f2
done
